chore: integ環境構築 android

diff --git a/.github/workflows/ko_beginner_ios.yml b/.github/workflows/ko_beginner_ios.yml
--- a/.github/workflows/ko_beginner_ios.yml
+++ b/.github/workflows/ko_beginner_ios.yml
@@ -54,6 +54,21 @@ jobs:
       - name: melos test
         run: |
           fvm dart pub global run melos unit_test
+          
+           # Upload results of failed Golden tests if test command failed.
+          if [ $? -ne 0 ]; then
+            # Finds all "failures" folders and copies them to the export
+            # directory. Therefore, we are able to view the results of the
+            # failed Golden tests.
+            #
+            # The command will use the exit code 0 (success) even when there are
+            # no failures folders.
+            find * -path '**/failures' -execdir bash -c "cp -r failures $FCI_EXPORT_DIR" \;
+
+            # Because we caught the exit code of the test command, we need to
+            # set manually again.
+            exit 1
+          fi
 
       - name: Add GoogleService-Info.plist
         run: echo "${{ secrets.KO_BEGINNER_GOOGLE_SERVICES_INFO_BASE64 }}" | base64 -d > apps/ko_beginner/ios/prod/GoogleService-Info.plist
